### ISSUE TITLE
Error when trying to fetch and build after creating repository

### ISSUE THREAD

**Issue by aliencrash** [odoo/runbot#250]
When you create a repository this error occur because for some motive it's not able to clone the repository. For this case the repo is configured to use poll mode.
Sometimes it works and sometime it doesn't.

2019-11-08 10:06:52,553 12979 ERROR runbot odoo.addons.base.ir.ir_cron: Call from cron Fetch and Schedule for server action #141 failed in Job #12
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/odoo-11.0.post20191031-py3.7.egg/odoo/models.py", line 4414, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/odoo-11.0.post20191031-py3.7.egg/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 10, in <module>
  File "/home/odoo/runbot/runbot/models/repo.py", line 554, in _cron_fetch_and_schedule
    repos._create_pending_builds()
  File "/home/odoo/runbot/runbot/models/repo.py", line 355, in _create_pending_builds
    repo._find_new_commits(refs[repo], ref_branches[repo])
  File "/home/odoo/runbot/runbot/models/repo.py", line 319, in _find_new_commits
    new_build = Build.create(build_info)
  File "/home/odoo/runbot/runbot/models/build.py", line 227, in create
    last_commit = closest_branch_repo._git_rev_parse(closest_name)
  File "/home/odoo/runbot/runbot/models/repo.py", line 134, in _git_rev_parse
    return self._git(['rev-parse', branch_name]).strip()
  File "/home/odoo/runbot/runbot/models/repo.py", line 128, in _git
    self.ensure_one()
  File "/usr/local/lib/python3.7/site-packages/odoo-11.0.post20191031-py3.7.egg/odoo/models.py", line 4417, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: runbot.repo()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/odoo-11.0.post20191031-py3.7.egg/odoo/addons/base/ir/ir_cron.py", line 102, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "/usr/local/lib/python3.7/site-packages/odoo-11.0.post20191031-py3.7.egg/odoo/addons/base/ir/ir_actions.py", line 557, in run
    res = func(action, eval_context=eval_context)
  File "/usr/local/lib/python3.7/site-packages/odoo-11.0.post20191031-py3.7.egg/odoo/addons/website/models/ir_actions.py", line 57, in run_action_code_multi
    res = super(ServerAction, self).run_action_code_multi(action, eval_context)
  File "/usr/local/lib/python3.7/site-packages/odoo-11.0.post20191031-py3.7.egg/odoo/addons/base/ir/ir_actions.py", line 433, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/usr/local/lib/python3.7/site-packages/odoo-11.0.post20191031-py3.7.egg/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/usr/local/lib/python3.7/site-packages/odoo-11.0.post20191031-py3.7.egg/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/odoo-11.0.post20191031-py3.7.egg/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 10, in <module>
  File "/home/odoo/runbot/runbot/models/repo.py", line 554, in _cron_fetch_and_schedule
    repos._create_pending_builds()
  File "/home/odoo/runbot/runbot/models/repo.py", line 355, in _create_pending_builds
    repo._find_new_commits(refs[repo], ref_branches[repo])
  File "/home/odoo/runbot/runbot/models/repo.py", line 319, in _find_new_commits
    new_build = Build.create(build_info)
  File "/home/odoo/runbot/runbot/models/build.py", line 227, in create
    last_commit = closest_branch_repo._git_rev_parse(closest_name)
  File "/home/odoo/runbot/runbot/models/repo.py", line 134, in _git_rev_parse
    return self._git(['rev-parse', branch_name]).strip()
  File "/home/odoo/runbot/runbot/models/repo.py", line 128, in _git
    self.ensure_one()
  File "/usr/local/lib/python3.7/site-packages/odoo-11.0.post20191031-py3.7.egg/odoo/models.py", line 4417, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: <class 'ValueError'>: "Expected singleton: runbot.repo()" while evaluating
'# Available variables:\n#  - env: Odoo Environment on which the action is triggered\n#  - model: Odoo Model of the record on which the action is triggered; is a void recordset\n#  - record: record on which the action is triggered; may be void\n#  - records: recordset of all records on which the action is triggered in multi-mode; may be void\n#  - time, datetime, dateutil, timezone: useful Python libraries\n#  - log: log(message, level=\'info\'): logging function to record debug information in ir.logging table\n#  - Warning: Warning Exception to use with raise\n# To return an action, assign: action = {...}\nmodel._cron_fetch_and_schedule("runbot.alien-group.com"),'

**Comment by Xavier-Do** [comment]
This is because you don't have any odoo/odoo branches in order to find the commit to use, because your odoo/odoo repo is disabled. 

I added a no_build field on repo, so that you can set odoo/odoo in poll mode with no_build set to true. It will only create branches, without builds.  

Note: as you may now, runbot is using branch name matching. So depending on the version you need for your addons, you have to prefix your branch with "version-". Example, to test addons with 12.0, your branch has to be called 12.0-feature_name.

**Comment by aliencrash** [comment]
Ok. I'm going to test it. I have a repository that is called just 13.0 would be suffice too? Cloning odoo is giving problems too.

**Comment by Xavier-Do** [comment]
Repository is not important, the branch name is the only think defining how a build will define his dependencies. This is why all our dev branches began with master-, 13.0-,  saas-12.3-, ... 
 
Cloning repo can be painful, it takes a lots of time especially if you don't have a good network or a slow hard drive. Good luck.
