### ISSUE TITLE
Fix: update cron should account for forward port failures

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#328]
Currently the forwardport.updates cron job doesn't seem to handle conflicts well: after odoo/odoo#45267 was updated the cron tried to update odoo/odoo#45360 to match. This never succeeded because the update conflicted (empty commit), leading to retrying (and re-failing) roughly every minute for 3 days (though since the server had other things to do it "only" created 24000 builds out of a possible 260000), ultimately ending with @Xavier-Do trying to knife @jvm-odoo. Which is not an ideal state of affairs.

* the update cron should behave properly if it gets a conflict and not blow up and retry
* the update cron should stop trying to update *closed* PRs, here @nim-odoo had closed  odoo/odoo#45360 about an hour after odoo/odoo#45267 so there wasn't even a reason to update it

Although check: might be the issue was in fact that the cron was trying to update a closed PR? Unclear.

**Comment by xmo-odoo** [comment]
Note: apparently the part which systematically failed was the check on the PR head
```
2020-02-14 07:39:37,026 32297 ERROR mergebot odoo.addons.forwardport.models.forwardport: Error while processing forwardport.updates(23,), skipping 
Traceback (most recent call last):
  File "/home/odoo/src/runbot/forwardport/models/forwardport.py", line 25, in _process
    b._process_item()
  File "/home/odoo/src/runbot/forwardport/models/forwardport.py", line 96, in _process_item
    child.target, child.refname, s)
  File "/home/odoo/src/runbot/forwardport/models/project.py", line 756, in _create_fp_branch
    source.cat_file(e=self.head)
  File "/home/odoo/src/runbot/forwardport/models/project.py", line 1071, in __call__
    return self._repo._run(self._name, *args, *self._to_options(kwargs))
  File "/home/odoo/src/runbot/forwardport/models/project.py", line 1026, in _run
    **opts
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('git', '-C', '/home/odoo/.cache/forwardport/odoo/odoo', 'cat-file', '-e', '8b45d1f22d5097a7376eae19c69be984f59b35bd')' returned non-zero exit status 1.
```
however the head being checked changes every time which is weird. Though this does *not* seem to be an issue in the next iteration.

**Comment by xmo-odoo** [comment]
> Although check: might be the issue was in fact that the cron was trying to update a closed PR? 

Occurred again with #8444 (due to an update to #8440) which has no conflicts so looks like it's really that, the forwardbot chokes when trying to update a closed PR (from a non-closed one).
