### ISSUE TITLE
Error when opening /runbot without logging in

### ISSUE THREAD

**Issue by obayit** [odoo/runbot#362]
FYI I have at least "Internal User" group for the "Limited to groups" field on all my repositories.
Error from log: 
```
2020-04-12 07:42:46,880 9599 ERROR runbot odoo.addons.http_routing.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_runbot_repo_327
  File "<template>", line 2, in body_call_content_325
  File "<template>", line 8, in set_289
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/http.py", line 804, in dispatch
    r = self._call_function(**self.params)
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/http.py", line 341, in checked_call
    result.flatten()
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/http.py", line 1231, in flatten
    self.response.append(self.render())
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/http.py", line 1224, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/addons/base/models/ir_u
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/addons/website/models/ir_ui_view.py", line 345, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/addons/web_editor/models/ir_ui_view.py", line 25, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/addons/base/models/ir_ui_view.py", line 1182, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/addons/base/models/qweb.py", line 339, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/home/odoo/src/odoo-13.0.post20200326/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_runbot_repo_327
  File "<template>", line 2, in body_call_content_325
  File "<template>", line 8, in set_289
TypeError: 'NoneType' object is not callable

Error to render compiling AST
TypeError: 'NoneType' object is not callable
Template: runbot.repo
Path: /t/t/t[2]/form
Node: <form class="form-inline my-2 my-lg-0" role="search" t-att-action="qu(search='')" method="get">
                  <div class="input-group md-form form-sm form-2 pl-0">
                    <input class="form-control my-0 py-1 red-border" type="text" placeholder="Search" aria-label="Search" name="search" t-att-value="search"/>
                    <div class="input-group-append">
                      <button type="submit" class="input-group-text red lighten-3" id="basic-text1"><i class="fa fa-search text-grey"/></button>
                    </div>
                  </div>
                </form>

```

Probably a typo here `qu(search='')`

**Comment by obayit** [comment]
Tried with one repository without groups restriction and it is working fine.
I think having all private repositories is not one of the current goals of this repo
