### ISSUE TITLE
doo.exceptions.AccessError: ("Sorry, you are not allowed to create documents of type 'Repo reftime' (runbot.repo.reftime). No group currently allows this operation.

### ISSUE THREAD

**Issue by aliencrash** [odoo/runbot#365]
I think it's missing the creating permission for the model runbot.repo.reftime

Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/models/repo.py", line 378, in _create_pending_builds
    ref = repo._get_refs()
  File "/home/odoo/runbot/runbot/models/repo.py", line 285, in _get_refs
    self.set_ref_time(get_ref_time)
  File "/home/odoo/runbot/runbot/models/repo.py", line 115, in set_ref_time
    self.env['runbot.repo.reftime'].create({'time': value, 'repo_id': repo.id})
  File "<decorator-gen-3>", line 2, in create
  File "/usr/local/lib/python3.7/site-packages/odoo-13.0.post20200415-py3.7.egg/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/usr/local/lib/python3.7/site-packages/odoo-13.0.post20200415-py3.7.egg/odoo/models.py", line 3672, in create
    self.check_access_rights('create')
  File "/usr/local/lib/python3.7/site-packages/odoo-13.0.post20200415-py3.7.egg/odoo/models.py", line 3213, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-22>", line 2, in check
  File "/usr/local/lib/python3.7/site-packages/odoo-13.0.post20200415-py3.7.egg/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo-13.0.post20200415-py3.7.egg/odoo/addons/base/models/ir_model.py", line 1549, in check
    raise AccessError(msg % msg_params)
odoo.exceptions.AccessError: ("Sorry, you are not allowed to create documents of type 'Repo reftime' (runbot.repo.reftime). No group currently allows this operation. - (Operation: create, User: 2)", None)

**Comment by obayit** [comment]
The only `ir.model.access` for that model is
`access_runbot_repo_reftime,runbot_repo_reftime,runbot.model_runbot_repo_reftime,group_user,1,0,0,0`

**Comment by Xavier-Do** [comment]
"_create_pending_builds" is only supposed to be executed as root in a cron. You can change access right by hand if you really need to call it manually.
