### ISSUE TITLE
Exception on fetching odoo github repository

### ISSUE THREAD

**Issue by aliencrash** [odoo/runbot#368]
version 13.0 
I'm trying this new runbot version. The Odoo repository it's configured, but after cloning it's not getting the branches information. The log show the following errors on trying to get the information.

2020-05-05 23:32:29,228 572821 ERROR runbot odoo.addons.runbot.models.repo: Ignored github error https://api.github.com/repos/odoo/odoo/pulls/50189 None (try 3/2) 
Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/models/repo.py", line 256, in _github
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/repos/odoo/odoo/pulls/50189
2020-05-05 23:32:32,160 572821 ERROR runbot odoo.addons.runbot.models.repo: Ignored github error https://api.github.com/repos/odoo/odoo/pulls/50558 None (try 3/2) 
Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/models/repo.py", line 256, in _github
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/repos/odoo/odoo/pulls/50558
2020-05-05 23:32:34,518 572814 INFO runbot longpolling: 41.205.36.244 - - [2020-05-05 23:32:34] "POST /longpolling/poll HTTP/1.0" 200 408 50.065164 
2020-05-05 23:32:35,058 572821 ERROR runbot odoo.addons.runbot.models.repo: Ignored github error https://api.github.com/repos/odoo/odoo/pulls/50484 None (try 3/2) 
Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/models/repo.py", line 256, in _github
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/repos/odoo/odoo/pulls/50484
2020-05-05 23:32:37,966 572821 ERROR runbot odoo.addons.runbot.models.repo: Ignored github error https://api.github.com/repos/odoo/odoo/pulls/50315 None (try 3/2) 
Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/models/repo.py", line 256, in _github
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/repos/odoo/odoo/pulls/50315

**Comment by Xavier-Do** [comment]
Sorry for the long delay

What do you mean with "new runbot version".

We just merged the runbot 5.0 but in may it was the what I would call "old runbot version".

**Comment by xmo-odoo** [comment]
@aliencrash you might not have put in an oauth token, or might not have put one with the correct scopes? 

One thing you could do is edit the code to dump the response headers, github errors are not very informative but on unauthorized accesses one of the headers *should* tell you what scopes the endpoint requires.
