### ISSUE TITLE
Investigate PR edition / update possibly breaking the "does this need to be forward-ported" cron

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#457]
May or may not be a dupe of #451

odoo/odoo#64706 got merged which created odoo/odoo#65275, odoo/odoo#65279 and odoo/odoo#65282 (so far so good)

Then odoo/odoo#65275 got edited, which spawned odoo/odoo#65405 and odoo/odoo#65412, then the edition-forwarding thing started blowin up because in trying to apply the update to odoo/odoo#65275 is kept finding two child PRs (incidentally the update cron may want to handle that case somehow)

**Comment by xmo-odoo** [comment]
One more case:

* https://github.com/odoo/enterprise/pull/16357
* merged and forwardported up to master
* https://github.com/odoo/enterprise/pull/16371 (14.0 fw) force-pushed
* which made https://github.com/odoo/enterprise/pull/16375 blow a gasket

there's an error
```
2021-02-16 08:11:11,490 7492 ERROR mergebot odoo.addons.forwardport.models.forwardport: Error while processing forwardport.updates(98,), skipping 
Traceback (most recent call last):
  File "runbot/forwardport/models/forwardport.py", line 25, in _process
    b._process_item()
  File "runbot/forwardport/models/forwardport.py", line 117, in _process_item
    child.target, child.refname, s)
  File "runbot/forwardport/models/project.py", line 788, in _create_fp_branch
    source.cat_file(e=self.head)
  File "runbot/forwardport/models/project.py", line 1118, in __call__
    return self._repo._run(self._name, *args, *self._to_options(kwargs))
  File "runbot/forwardport/models/project.py", line 1073, in _run
    **opts
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('git', '-C', '/home/odoo/.cache/forwardport/odoo/enterprise', 'cat-file', '-e', '1e8ec40241b58018b8bc076af91c5a85ed32f1f5')' returned non-zero exit status 1.
```
although this error may not have come from this specific forward-port, it's present multiple times in the log with different commit hashes.

So is this one:
```
2021-02-16 08:10:54,839 7492 ERROR mergebot odoo.addons.forwardport.models.forwardport: Error while processing forwardport.updates(95,), skipping 
Traceback (most recent call last):
  File "odoo/13.0/odoo/models.py", line 5101, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runbot/forwardport/models/forwardport.py", line 25, in _process
    b._process_item()
  File "runbot/forwardport/models/forwardport.py", line 96, in _process_item
    child.display_name,
  File "odoo/13.0/odoo/fields.py", line 988, in __get__
    record.ensure_one()
  File "odoo/13.0/odoo/models.py", line 5104, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: runbot_merge.pull_requests(59555, 59381)
2021-02-16 08:10:54,883 7492 ERROR mergebot odoo.addons.forwardport.models.forwardport: Error while processing forwardport.updates(96,), skipping 
Traceback (most recent call last):
  File "odoo/13.0/odoo/models.py", line 5101, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runbot/forwardport/models/forwardport.py", line 25, in _process
    b._process_item()
  File "runbot/forwardport/models/forwardport.py", line 96, in _process_item
    child.display_name,
  File "odoo/13.0/odoo/fields.py", line 988, in __get__
    record.ensure_one()
  File "odoo/13.0/odoo/models.py", line 5104, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: runbot_merge.pull_requests(59555, 59381)
2021-02-16 08:10:54,904 7492 ERROR mergebot odoo.addons.forwardport.models.forwardport: Error while processing forwardport.updates(97,), skipping 
Traceback (most recent call last):
  File "odoo/13.0/odoo/models.py", line 5101, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runbot/forwardport/models/forwardport.py", line 25, in _process
    b._process_item()
  File "runbot/forwardport/models/forwardport.py", line 96, in _process_item
    child.display_name,
  File "odoo/13.0/odoo/fields.py", line 988, in __get__
    record.ensure_one()
  File "odoo/13.0/odoo/models.py", line 5104, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: runbot_merge.pull_requests(59570, 59525)
```

**Comment by xmo-odoo** [comment]
Other PRs with the issue, which also created duplicates:
* odoo/odoo#66078
* odoo/odoo#66176

**Comment by xmo-odoo** [comment]
For 66078: [truncated log](https://github.com/odoo/runbot/files/5987354/openerp-13.0.log.gz), only contains the section which mentions 66091 (the edition of which triggered the issue)

[Full log of the entire day.](https://github.com/odoo/runbot/files/5987356/openerp-13.0.full.log.gz)

Notes:
* both files are encrypted with age / rage, but no extension because github is a dummy
* the full log is actually compressed with xz (then encrypted), but uses the `gz` extension because github is a dummy

**Comment by xmo-odoo** [comment]
[zbsm.zip](https://github.com/odoo/runbot/files/5987449/zbsm.zip)
