### ISSUE TITLE
Cron errors not being fed to sentry?

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#471]
Got an error in a cron last week:
```
2021-03-22 17:00:00,332 29559 ERROR mergebot odoo.addons.forwardport.models.forwardport: Error while processing forwardport.batches(34198,), skipping 
Traceback (most recent call last):
  File "forwardport/models/forwardport.py", line 26, in _process
    b._process_item()
  File "/home/odoo/src/runbot/forwardport/models/forwardport.py", line 53, in _process_item
    newbatch = batch.prs._port_forward()
  File "forwardport/models/project.py", line 661, in _port_forward
    results = r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
This error did not appear in sentry, there are two possibilities here:

* logging.exception fails to reach sentry
* having silenced the ping errors in sentry (https://sentry.io/organizations/online/issues/2034184415) leads to all JSONDecodeError being ignored

**Comment by xmo-odoo** [comment]
Issue seem to be specifically that log calls from the Queue subclasses don't get picked up. I don't really get why, I don't see any special log configuration or anything.

For now I've updated `sentry_sdk` to 1.3.1, we'll see how that goes.
