### ISSUE TITLE
Error on first build

### ISSUE THREAD

**Issue by obayit** [odoo/runbot#498]
I followed the instruction in the README file but got an error on the first build.

The first build is stuck at `preparing`:

![screenshot-161 35 32 85-2021 07 06-13_53_33](https://user-images.githubusercontent.com/20386024/124595668-95b82780-de61-11eb-8bcd-598dfc595ead.png)

Versions contains:

![screenshot-161 35 32 85-2021 07 06-13_54_03](https://user-images.githubusercontent.com/20386024/124595731-ac5e7e80-de61-11eb-944f-a35997a64c1c.png)

I guess this is the bundle:

![screenshot-161 35 32 85-2021 07 06-13_57_04](https://user-images.githubusercontent.com/20386024/124596147-39a1d300-de62-11eb-8148-e07b938f34bc.png)

The stack trace is:
```
2021-07-06 12:38:01,550 9691 ERROR runbot odoo.addons.runbot.models.batch: No version found on bundle 14.0-dev-dummy in project R&D 
2021-07-06 12:38:01,550 9691 ERROR runbot odoo.addons.runbot.models.batch: No dockerfile found ! 
2021-07-06 12:38:01,567 9691 WARNING runbot odoo.addons.runbot.models.batch: batch 1: No base head found for repo assets 
2021-07-06 11:59:11,736 8264 ERROR runbot odoo.sql_db: bad query: INSERT INTO "runbot_build_params" ("id", "create_uid", "create_date", "write_uid", "w
rite_date", "config_data", "config_id", "create_batch_id", "dockerfile_id", "dump_db", "extra_params", "fingerprint", "modules", "project_id", "skip_re
quirements", "trigger_id", "upgrade_from_build_id", "upgrade_to_build_id", "version_id") VALUES (nextval('runbot_build_params_id_seq'), 1, (now() at ti
me zone 'UTC'), 1, (now() at time zone 'UTC'), NULL, 1, 1, NULL, NULL, '', 'e0e2ba055025144c584b5e2994c39bff2f6b687fd440f17431ea2def04990403', NULL, 1,
 false, 1, NULL, NULL, NULL) RETURNING id
ERROR: null value in column "version_id" violates not-null constraint
DETAIL:  Failing row contains (694, null, 1, 1, 1, null, null, f, , 1, null, null, null, null, null, e0e2ba055025144c584b5e2994c39bff2f6b687fd440f17431
ea2def04990403, 1, 2021-07-06 11:59:11.689435, 1, 2021-07-06 11:59:11.689435).
 
2021-07-06 11:59:11,736 8264 ERROR runbot odoo.addons.base.models.ir_cron: Call from cron Runbot for server action #164 failed in Job #13 
Traceback (most recent call last):
  File "/opt/odoo13/src/odoo13/odoo/tools/safe_eval.py", line 354, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo13/src/runbot/runbot/models/runbot.py", line 255, in _cron
    batch._process()
  File "/opt/odoo13/src/runbot/runbot/models/batch.py", line 95, in _process
    batch._prepare()
  File "/opt/odoo13/src/runbot/runbot/models/batch.py", line 297, in _prepare
    params = self.env['runbot.build.params'].create(params_value)
  File "/opt/odoo13/src/runbot/runbot/models/build.py", line 110, in create
    return super().create(values)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo13/src/odoo13/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo13/src/odoo13/odoo/models.py", line 3810, in create
    records = self._create(data_list)
  File "/opt/odoo13/src/odoo13/odoo/models.py", line 3916, in _create
    cr.execute(query, params)
  File "/opt/odoo13/src/odoo13/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo13/src/odoo13/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "version_id" violates not-null constraint
DETAIL:  Failing row contains (694, null, 1, 1, 1, null, null, f, , 1, null, null, null, null, null, e0e2ba055025144c584b5e2994c39bff2f6b687fd440f17431
ea2def04990403, 1, 2021-07-06 11:59:11.689435, 1, 2021-07-06 11:59:11.689435).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/src/odoo13/odoo/addons/base/models/ir_cron.py", line 110, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "/opt/odoo13/src/odoo13/odoo/addons/base/models/ir_actions.py", line 537, in run
    res = func(action, eval_context=eval_context)
  File "/opt/odoo13/src/odoo13/addons/website/models/ir_actions.py", line 59, in run_action_code_multi
    res = super(ServerAction, self).run_action_code_multi(action, eval_context)
  File "/opt/odoo13/src/odoo13/odoo/addons/base/models/ir_actions.py", line 422, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/opt/odoo13/src/odoo13/odoo/tools/safe_eval.py", line 377, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/opt/odoo13/src/odoo13/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo13/src/odoo13/odoo/tools/safe_eval.py", line 354, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo13/src/runbot/runbot/models/runbot.py", line 255, in _cron
    batch._process()
  File "/opt/odoo13/src/runbot/runbot/models/batch.py", line 95, in _process
    batch._prepare()
  File "/opt/odoo13/src/runbot/runbot/models/batch.py", line 297, in _prepare
    params = self.env['runbot.build.params'].create(params_value)
  File "/opt/odoo13/src/runbot/runbot/models/build.py", line 110, in create
    return super().create(values)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo13/src/odoo13/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo13/src/odoo13/odoo/models.py", line 3810, in create
    records = self._create(data_list)
  File "/opt/odoo13/src/odoo13/odoo/models.py", line 3916, in _create
    cr.execute(query, params)
  File "/opt/odoo13/src/odoo13/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo13/src/odoo13/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
ValueError: <class 'psycopg2.IntegrityError'>: "null value in column "version_id" violates not-null constraint
DETAIL:  Failing row contains (694, null, 1, 1, 1, null, null, f, , 1, null, null, null, null, null, e0e2ba055025144c584b5e2994c39bff2f6b687fd440f17431ea2def04990403, 1, 2021-07-06 11:59:11.689435, 1, 2021-07-06 11:59:11.689435).
" while evaluating
'model._cron()'
```

*Edit:* add more log

**Comment by obayit** [comment]
I found that there was not `bundle` marked as `base` for my repository.
After I set one to `base` the build is no longer stuck at `preparing`

But now the build is stuck at `pending`

**Comment by obayit** [comment]
I created a new project and it worked!
