### ISSUE TITLE
Creating `runbot.version` from the UI causes an error.

### ISSUE THREAD

**Issue by obayit** [odoo/runbot#564]
Steps to reproduce:
Go to Runbot > Bundle > Versions, then click Create

Error:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/src/vs/odoo13/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/src/vs/odoo13/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/src/vs/odoo13/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/src/vs/odoo13/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/src/vs/odoo13/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/src/vs/odoo13/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/src/vs/odoo13/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/src/vs/odoo13/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/src/vs/odoo13/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/src/vs/odoo13/addons/web/controllers/main.py", line 1339, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/src/vs/odoo13/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/src/vs/odoo13/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/src/vs/odoo13/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/src/vs/odoo13/odoo/models.py", line 6243, in onchange
    value = record[name]
  File "/opt/odoo/src/vs/odoo13/odoo/models.py", line 5739, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/src/vs/odoo13/odoo/fields.py", line 1031, in __get__
    self.compute_value(recs)
  File "/opt/odoo/src/vs/odoo13/odoo/fields.py", line 1145, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/src/vs/odoo13/odoo/models.py", line 4011, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo/src/runbot/runbot/models/version.py", line 36, in _compute_version_number
    version.number = '.'.join([elem.zfill(2) for elem in re.sub(r'[^0-9\.]', '', version.name).split('.')])
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```
The only way I was able to create a version was by duplicating the existing master version.
Should we even create versions manually?

**Comment by Xavier-Do** [comment]
I don't think you ever need to create a version manually. Versions are automatically created for base bundles (bundle matching runbot_is_base_regex icp) Runbot should do most of the work automatically, you are only supposed to configure repos, remotes and triggers. 

Versions configuration should only be used to define a specific dockerfile_id or a sequence if the automatic number detection fails (only usefull for upgrades).

**Comment by obayit** [comment]
Yeah it is created here:
```
    @api.depends('is_base', 'base_id.version_id')
    def _compute_version_id(self):
        for bundle in self.sorted(key='is_base', reverse=True):
            if not bundle.is_base:
                bundle.version_id = bundle.base_id.version_id
                continue
            bundle.version_id = self.env['runbot.version']._get(bundle.name)
```

But for some reason, in my installation it didn't :(
