### ISSUE TITLE
Problem with runbot bootstrap

### ISSUE THREAD

**Issue by yustas147** [odoo/runbot#572]
Having installed clean odoo13.0  database with runbot module (13.0.5.1), following the guide from Readme.md ,
got this error:
----
2022-01-22 18:13:19,608 31053 ERROR first13 odoo.addons.base.models.ir_cron: Call from cron Runbot for server action #164 failed in Job #13
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_cron.py", line 110, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "/opt/odoo/odoo/addons/base/models/ir_actions.py", line 537, in run
    res = func(action, eval_context=eval_context)
  File "/opt/odoo/addons/website/models/ir_actions.py", line 59, in run_action_code_multi
    res = super(ServerAction, self).run_action_code_multi(action, eval_context)
  File "/opt/odoo/odoo/addons/base/models/ir_actions.py", line 422, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/opt/odoo/odoo/tools/safe_eval.py", line 360, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo13/extra-addons/runbot/models/runbot.py", line 215, in _cron
    host.set_psql_conn_count()
  File "/opt/odoo13/extra-addons/runbot/models/host.py", line 108, in set_psql_conn_count
    with local_pgadmin_cursor() as local_cr:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/odoo13/extra-addons/runbot/common.py", line 101, in local_pgadmin_cursor
    cnx = psycopg2.connect("dbname=postgres")
  File "/opt/venvOdoo13python36/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied
----
any help would be greatly appreciated

**Comment by yustas147** [comment]
.... needed to use trust authentication in pg_hba.conf
