### ISSUE TITLE
Error when creating runbot.build.params record

### ISSUE THREAD

**Issue by M-Saeb** [odoo/runbot#655]
going to runbot.build.params form view to create a new record:

### What I expected
The record is created succefully

### What I got 
An ORM error
```
Traceback (most recent call last):
  File "/odoo15/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo15/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/odoo15/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo15/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo15/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo15/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/odoo15/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/odoo15/odoo/addons/web/controllers/main.py", line 1347, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo15/odoo/addons/web/controllers/main.py", line 1339, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo15/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo15/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo15/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo15/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: create() missing 1 required positional argument: 'values'
```

### My Build
I'm running odoo15 from source code from branch 15.0 and runbot from branch 15.0
the configuration file:
```
[options]
limit_memory_hard = 4311744512
limit_memory_soft = 4294967296
limit_time_real_cron = 1800
dev=xml,reload,qweb
db_name=15-runbot
; dbfilter=15-*.
addons_path=/odoo15/enterprise,/odoo15/odoo/addons,/odoo15/c-addons/runbot
```

**Comment by Xavier-Do** [comment]
In the last version it should work by adding the project_id in the view form.

Anyway runbot_params is more a technical model, the view form is mainly here to check what the params were and should be reaonly, there is no real use case to create params from the interface. To test custom behaviour, we generaly do that using python steps creating sub builds with the add_child method in order to generate custom test behaviour with  specific params when a new commit is detected.
